name: Deploy in SFDC
on:
  pull_request:
    types: [synchronize]
    branches: [master]
    paths:
      - "force-app/**"
  push:
    branches: [master]
    paths:
      - "force-app/**"
jobs:
  steps-to-deploy:
    runs-on: ubuntu-latest
    container: 
      image: salesforce/salesforcedx:latest-full
    steps:
      # * Check repo and previous commits for delta deploy (SFDX plugin)
      - uses: actions/checkout@v3
        with:
          # ref: ${{github.ref}}
          fetch-depth: 0
          # if: github.event_name == 'push' || github.event.action == 'synchronize'
      # * Use Node 16 for SFDX CLI
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      # * Update CLI (just in case)
      - name: Update CLI
        run: |
          sfdx update
      # * Install SFDX Delta plugin (deploy only detected changes)
      - name: Install SFDX Git Delta
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
      # * Install SFDX Scanner plugin (check PMD rules in the repo) and check list of plugins
      # - name: Install SFDX Scanner
      #   run: |
      #     echo y | sfdx plugins:install @salesforce/sfdx-scanner
      #     sfdx plugins
      # * Add URL from secret in repo
      - name: Add URL from repo
        shell: bash
        run: 'echo ${{secrets.SFDX_AUTH_URI}} > INSTANCE_URL'
      # * Login in SFDC instance
      - name: Login in Salesforce
        run: |
          sfdx force:auth:sfdxurl:store -f INSTANCE_URL -s -a sfdcInstance
          echo ${{github.sha}} __ ${{github.event.before}}
      # * Deploy Delta changes
      - name: Create Delta
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .
      # * Deploy changes
      - name: Deploy to SFDC
        run: |
          sfdx force:source:deploy -x package/package.xml --postdestructivechanges destructiveChanges/destructiveChanges.xml