name: Deploy in SFDC
on:
  pull_request:
    types: [synchronize]
    branches: [master]
    paths:
      - "force-app/**"
  push:
    branches: [master]
    paths:
      - "force-app/**"
jobs:
  steps-to-deploy:
    runs-on: ubuntu-latest
    container: 
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      # * Check repo and previous commits for delta deploy (SFDX plugin)
      - uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          fetch-depth: 0
      # * Use Node 16 for SFDX CLI
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      # * Update CLI (just in case)
      - name: Update CLI
        run: |
          sfdx update
          git config --global --add safe.directory /__w/personalSFDC/personalSFDC
      # * Install SFDX Delta plugin (deploy only detected changes)
      - name: Install SFDX Git Delta
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
      # * Install SFDX Scanner plugin (check PMD rules in the repo) and check list of plugins
      # - name: Install SFDX Scanner
      #   run: |
      #     echo y | sfdx plugins:install @salesforce/sfdx-scanner
      #     sfdx plugins
      # * Add URL from secret in repo
      - name: Add URL from repo
        shell: bash
        run: 'echo ${{secrets.SFDX_AUTH_URI}} > INSTANCE_URL'
      # * Login in SFDC instance
      - name: Login in Salesforce
        run: |
          sfdx force:auth:sfdxurl:store -f INSTANCE_URL -s -a sfdcInstance
      # * Deploy Delta changes
      - name: Create Delta
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --generate-delta --output . --source force-app/
      # * Run Specified tests
      - name: Run one tests
        run: |
          sfdx force:apex:test:run --synchronous --classnames "AccountManagerTest"
      # * Run wrong test
      - name: Run wrong test
        run: |
          sfdx force:apex:test:run --synchronous --classnames "AccountManagerTes"
      # * Run Tests
      - name: Run All tests
        run: |
          sfdx force:apex:test:run --synchronous --testlevel RunLocalTests
      # * Deploy changes
      - name: Deploy to SFDC
        run: |
          sfdx force:source:deploy -x package/package.xml --postdestructivechanges destructiveChanges/destructiveChanges.xml