name: Deploy in SFDC
run-name: Deploy in ${{GITHUB.REF_NAME}}
on:
  push:
    branches: [master]
    paths:
      - "force-app/**"
jobs:
  steps-to-deploy:
    runs-on: ubuntu-latest
    container: 
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      # * Check repo and previous commits for delta deploy (SFDX plugin)
      - name: Add repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          fetch-depth: 0
      # * Use Node 16 for SFDX CLI
      - name: NodeJs
        uses: actions/setup-node@v3
        with:
          check-latest: true
      # * Update CLI (just in case)
      - name: Update CLI
        run: |
          sfdx update
          git config --global --add safe.directory /__w/personalSFDC/personalSFDC
      # * Install SFDX Delta plugin (deploy only detected changes)
      - name: Install SFDX Git Delta
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
      # * Install SFDX Scanner plugin (check PMD rules in the repo) and check list of plugins
      - name: Install SFDX Scanner
        if: ${{GITHUB.REF_NAME == 'test'}}
        run: |
          echo y | sfdx plugins:install @salesforce/sfdx-scanner
          sfdx plugins
      # * Add URL from secret in repo
      - name: Add URL from repo ans get tests
        shell: bash
        run: |
          echo ${{secrets.SFDX_AUTH_URI}} > INSTANCE_URL
          TESTS=$(cat tests/master.csv)
          echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
      # * Login in SFDC instance
      - name: Login in Salesforce
        run: |
          echo ${{GITHUB.REF_NAME}}
          sfdx force:auth:sfdxurl:store -f INSTANCE_URL -s -a sfdcInstance
      # * Create Delta changes
      - name: Create Delta
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --generate-delta --output . --source force-app/
      # * Deploy without tests
      - name: Functional deploy
        if: ${{env.APEX_TESTS == 'No' || env.APEX_TESTS == 'NO' || env.APEX_TESTS == 'no' || env.APEX_TESTS == ''}}
        run: |
          sfdx force:source:deploy --manifest package/package.xml --testlevel RunSpecifiedTests --runtests skip --postdestructivechanges destructiveChanges/destructiveChanges.xml --verbose
      # # * Deploy specified Tests
      - name: Deploy with specific Tests
        if: ${{env.APEX_TESTS != '' && env.APEX_TESTS != 'All' && env.APEX_TESTS != 'all' && env.APEX_TESTS != 'No' && env.APEX_TESTS != 'NO' && env.APEX_TESTS != 'no'}}
        run: |
          sfdx force:source:deploy --manifest package/package.xml --testlevel RunSpecifiedTests --runtests ${{env.APEX_TESTS}} --postdestructivechanges destructiveChanges/destructiveChanges.xml --verbose
      # * Deploy All Tests
      - name: Deploy  with All Tests
        if: ${{env.APEX_TESTS == 'ALL' || env.APEX_TESTS == 'All' || env.APEX_TESTS == 'all'}}
        run: |
          sfdx force:source:deploy -x package/package.xml --testlevel RunLocalTests --postdestructivechanges destructiveChanges/destructiveChanges.xml --verbose