name: Deploy in SFDC
on:
  pull_request:
    types: [synchronize]
    branches: [main]
    paths:
      - "force-app/**"
jobs:
  steps-to-deploy:
    runs-on: ubuntu-latest
    container: 
      image: salesforce/salesforcedx:latest-full
    steps:
      # * Check repo and previous commits for delta deploy (SFDX plugin)
      - uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          fetch-depth: 0
          # if: github.event_name == 'push' || github.event.action == 'synchronize'
      # * Use Node 16 for SFDX CLI
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      # * Install SFDX CLI
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      # * Install SFDX Delta plugin (deploy only detected changes)
      - name: Install SFDX Git Delta
        run: |
          eco y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
          node_modules/sfdx-cli/bin/run plugins
      # * Check list of plugins
      # - name: SFDX Plugins
      #   run: |
      #     node_modules/sfdx-cli/bin/run sfdx plugins
      # * Install SFDX Scanner plugin (check PMD rules in the repo)
      - name: Install SFDX Scanner
        run: |
          echo y | node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
          node_modules/sfdx-cli/bin/run plugins
      # * Add URL from secret in repo
      - name: Add URL from repo
        shell: bash
        run: 'echo ${{secrets.SFDX_AUTH_URI}} > INSTANCE_URL'
      # * Login in SFDC instance
      - name: Login in Salesforce
        run: |
          node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f INSTANCE_URL -s -a sfdcInstance
      