name: Validate incoming PR
run-name: Validate change of ${{GITHUB.EVENT.PULL_REQUEST.TITLE}} in ${{GITHUB.BASE_REF}}
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches: [test, master]
    paths:
      - "force-app/**"
jobs:
  Validation-of-deploy:
    runs-on: ubuntu-latest
    container: 
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      # * Check repo and previous commits for delta deploy (SFDX plugin)
      - name: Add repo
        uses: actions/checkout@v3
        with:
          ref: ${{GITHUB.REF}}
          fetch-depth: 0
      # * Use Node for SFDX CLI
      - name: NodeJs version
        uses: actions/setup-node@v3
        with:
          check-latest: true
      # * Get Body of PR for list o tests
      - name: Get Tests of PR
        env:
          PAYLOAD: ${{GITHUB.EVENT.PULL_REQUEST.BODY}}
        run: |
          echo $PAYLOAD > ./pr_body.txt
          node ./parsePR.js
          TESTS=$(cat testsToRun.txt)
          echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
      # * Update CLI (just in case)
      - name: Update CLI and add Safe directory
        run: |
          sfdx update
          git config --global --add safe.directory /__w/personalSFDC/personalSFDC
      # * Install SFDX Delta plugin (deploy only detected changes)
      - name: Install SFDX Git Delta
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins:install @salesforce/sfdx-scanner
          sfdx plugins
      # * Add URL from secret in repo
      - name: Add URL from repo ans get tests
        shell: bash
        run: |
          echo ${{secrets.SFDX_AUTH_URI}} > ./INSTANCE_URL.json
      # * Login in SFDC instance
      - name: Login in Salesforce
        run: |
          sf org login sfdx-url --sfdx-url-file ./INSTANCE_URL.json --alias sfdcInstance
      # * Create Delta changes
      - name: Create Delta
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --generate-delta --output . --source force-app/
      # ! Scanner run
      - name: Scanner run
        shell: bash
        run: |
          sfdx scanner:run --format sarif --target 'force-app' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'
      # ! Scanner result upload
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: changed-sources/apexScanResults.sarif
      # * Validate without tests
      - name: Validate without Tests
        if: ${{env.APEX_TESTS == 'No' || env.APEX_TESTS == 'NO' || env.APEX_TESTS == 'no' || env.APEX_TESTS == ''}}
        run: |
          sf project deploy start --manifest package/package.xml --target-org sfdcInstance --dry-run --verbose
      # * Validate with specific Tests
      - name: Validate specific Tests
        if: ${{env.APEX_TESTS != '' && env.APEX_TESTS != 'All' && env.APEX_TESTS != 'all' && env.APEX_TESTS != 'No' && env.APEX_TESTS != 'NO' && env.APEX_TESTS != 'no'}}
        run: |
          sf project deploy validate --manifest package/package.xml --target-org sfdcInstance --test-level RunSpecifiedTests --tests ${{env.APEX_TESTS}} --verbose
      # * Validate with All Tests
      - name: Validate All Tests
        if: ${{env.APEX_TESTS == 'ALL' || env.APEX_TESTS == 'All' || env.APEX_TESTS == 'all'}}
        run: |
          sf project deploy validate --manifest package/package.xml --target-org sfdcInstance --test-level RunLocalTests --verbose